# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pizza_deliver.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13pizza_deliver.proto\" \n\x0cPizzaRequest\x12\x10\n\x08\x63ustomer\x18\x01 \x01(\t\"\x1c\n\rPizzaResponse\x12\x0b\n\x03rsp\x18\x01 \x01(\t2C\n\rPizzaDelivery\x12\x32\n\rdeliver_pizza\x12\r.PizzaRequest\x1a\x0e.PizzaResponse(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pizza_deliver_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_PIZZAREQUEST']._serialized_start=23
  _globals['_PIZZAREQUEST']._serialized_end=55
  _globals['_PIZZARESPONSE']._serialized_start=57
  _globals['_PIZZARESPONSE']._serialized_end=85
  _globals['_PIZZADELIVERY']._serialized_start=87
  _globals['_PIZZADELIVERY']._serialized_end=154
# @@protoc_insertion_point(module_scope)
